stages:
  - test
  - build
  - deploy

test:
  image: "rust:latest"
  stage: test
  tags:
    - docker-amd64
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends libudev-dev
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

windows:
  image: "rust:latest"
  tags:
    - docker-amd64
  variables:
    RUST_BUILDER: cargo
  stage: build
  before_script:
    - echo "Download dependencies"
    - apt-get update && apt-get --assume-yes install gcc-mingw-w64
    - rustup target add x86_64-pc-windows-gnu
  script:
    - make release-windows
  artifacts:
    paths:
      - release/

linux_x86_64:
  image: "rust:latest"
  tags:
    - docker-amd64
  variables:
    RUST_BUILDER: cargo
  stage: build
  before_script:
    - echo "Download dependencies"
    - apt-get update && apt-get --assume-yes install libssl-dev libudev-dev desktop-file-utils
    - echo "Setup appimagetool"
    - wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage -O /usr/local/bin/appimagetool
    - chmod +x /usr/local/bin/appimagetool
    - sed -i 's|AI\x02|\x00\x00\x00|' /usr/local/bin/appimagetool
    - rustup target add x86_64-unknown-linux-gnu
  script:
    - make release-linux-x86_64
  artifacts:
    paths:
      - release/

linux_aarch64:
  image: "rust:latest"
  tags:
    - docker-amd64
  variables:
    RUST_BUILDER: cargo
    CROSS_ARCH: arm64
    PKG_CONFIG_ALLOW_CROSS: 1
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
  stage: build
  before_script:
    - echo "Download dependencies"
    - dpkg --add-architecture ${CROSS_ARCH}
    - apt-get update && apt-get --assume-yes install libssl-dev:${CROSS_ARCH} libudev-dev:${CROSS_ARCH} desktop-file-utils gcc-aarch64-linux-gnu
    - echo "Setup appimagetool"
    - wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage -O /usr/local/bin/appimagetool
    - chmod +x /usr/local/bin/appimagetool
    - sed -i 's|AI\x02|\x00\x00\x00|' /usr/local/bin/appimagetool
    - rustup target add aarch64-unknown-linux-gnu
  script:
    - PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}" make release-linux-aarch64
  artifacts:
    paths:
      - release/

linux_arm:
  image: "rust:latest"
  tags:
    - docker-amd64
  variables:
    RUST_BUILDER: cargo
    CROSS_ARCH: armhf
    PKG_CONFIG_ALLOW_CROSS: 1
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
  stage: build
  before_script:
    - echo "Download dependencies"
    - dpkg --add-architecture ${CROSS_ARCH}
    - apt-get update && apt-get --assume-yes install libssl-dev:${CROSS_ARCH} libudev-dev:${CROSS_ARCH} desktop-file-utils gcc-arm-linux-gnueabihf
    - echo "Setup appimagetool"
    - wget https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage -O /usr/local/bin/appimagetool
    - chmod +x /usr/local/bin/appimagetool
    - sed -i 's|AI\x02|\x00\x00\x00|' /usr/local/bin/appimagetool
    - rustup target add armv7-unknown-linux-gnueabihf
  script:
    - PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig/:${PKG_CONFIG_PATH}" make release-linux-arm
  artifacts:
    paths:
      - release/
