[workspace]
resolver = "2"

members = [
	"bb-imager",
	"bb-imager-cli",
	"gui",
	"xtask",
]

[profile.release]
strip = true
lto = "thin"

[workspace.package]
version = "0.0.3"
edition = "2021"
authors = ["Ayush Singh <ayush@beagleboard.org>"]
repository = "https://openbeagle.org/ayush1325/bb-imager-rs"
license = "MIT"
