[workspace]
resolver = "2"

members = [
	"bb-flasher",
	"bb-imager-cli", "bb-flasher-pb2-mspm0",
	"bb-imager-gui", "bb-imager-service",
	"xtask", "bb-flasher-bcf", "bb-flasher-sd", "iced-loading", "bb-downloader", "bb-config",
]

[profile.release]
strip = true
lto = "thin"

[workspace.package]
version = "0.0.4"
edition = "2024"
authors = ["Ayush Singh <ayush@beagleboard.org>"]
repository = "https://openbeagle.org/ayush1325/bb-imager-rs"
license = "MIT"

[workspace.metadata.cross.target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libudev-dev:$CROSS_DEB_ARCH"
]

[workspace.metadata.cross.target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libudev-dev:$CROSS_DEB_ARCH"
]

[workspace.metadata.cross.target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libudev-dev:$CROSS_DEB_ARCH"
]
