[package]
name = "bb-imager"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
chrono = { version = "0.4.38", features = ["serde"] }
const-hex = { version = "1.12.0", features = ["serde"] }
crc32fast = "1.4.2"
fatfs = "0.3.6"
futures-core = "0.3.30"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serialport = "4.4.0"
thiserror = "1.0.63"
tracing = "0.1.40"
url = { version = "2.5.2", features = ["serde"] }
