[package]
name = "bb-imager"
version = "0.1.0"
edition = "2021"

[dependencies]
async-compression = { version = "0.4.12", features = ["tokio", "xz"] }
async-stream = "0.3.5"
chrono = { version = "0.4.38", features = ["serde"] }
const-hex = { version = "1.12.0", features = ["serde"] }
crc32fast = "1.4.2"
directories = "5.0.1"
# fatfs = "0.3.6"
futures-util = { version = "0.3.30", features = ["io"] }
reqwest = { version = "0.12.5", features = ["stream"] }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
serialport = "4.4.0"
sha2 = "0.10.8"
thiserror = "1.0.63"
tokio = { version = "1.39.1", features = ["fs"] }
tokio-util = { version = "0.7.11", features = ["io"] }
tracing = "0.1.40"
url = { version = "2.5.2", features = ["serde"] }
zip = "2.1.5"

[target.'cfg(target_os = "linux")'.dependencies]
udisks2 = { git = "https://github.com/FineFindus/udisks-rs.git" }
