[package]
name = "bb-imager"
version = "0.1.0"
edition = "2021"

[dependencies]
liblzma = { version = "0.3.3", features = ["static", "parallel"] }
chrono = { version = "0.4.38", features = ["serde"] }
const-hex = { version = "1.12.0", features = ["serde"] }
crc32fast = "1.4.2"
directories = "5.0.1"
reqwest = { version = "0.12.5", features = ["stream"] }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio-serial = "5.4.4"
sha2 = "0.10.8"
thiserror = "1.0.63"
tokio = { version = "1.39.1", default-features = false, features = ["rt-multi-thread", "process", "fs", "time", "sync"] }
tracing = "0.1.40"
url = { version = "2.5.2", features = ["serde"] }
zip = "2.1.5"
rs-drivelist = { git = "https://github.com/ir1keren/rs-drivelist.git" }
fatfs = "0.3.6"
fscommon = "0.1.1"
mbrman = "0.5.2"
hidapi = "2.6.3"
bin_file = { git = "https://gitlab.com/Ayush1325/bin_file.git", branch = "from-str" }
futures = "0.3.30"

[target.'cfg(target_os = "linux")'.dependencies]
udisks2 = "0.1.0"
tokio-serial = { version = "5.4.4", features = ["libudev"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58.0", features = ["Win32", "Win32_Storage", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System", "Win32_System_IO", "Win32_System_Ioctl"] }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.11.1"
