[package]
name = "bb-imager"
description = "Library to support bb-imager-cli and bb-imager-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
liblzma = { version = "0.3.6", features = ["static", "parallel"] }
chrono = { version = "0.4.39", optional = true , default-features = false }
const-hex = { version = "1.14.0" }
crc32fast = "1.4.2"
directories = "6.0.0"
reqwest = { version = "0.12.12", features = ["stream"] }
semver = { version = "1.0.25", optional = true }
serde = { version = "1.0.218", features = ["derive"], optional = true }
serde_json = { version = "1.0.139", optional = true }
sha2 = "0.10.8"
thiserror = "2.0.11"
tokio = { version = "1.43.0", default-features = false, features = ["rt-multi-thread", "process", "fs", "time"] }
tracing = "0.1.41"
url = "2.5.4"
bb-drivelist = "0.1.0"
fatfs = "0.3.6"
fscommon = "0.1.1"
mbrman = "0.5.4"
bin_file = "0.1.1"
futures = "0.3.31"
tempfile = "3.17.1"
cfg-if = "1.0.0"
bb-flasher-pb2-mspm0 = { path = "../bb-flasher-pb2-mspm0", optional = true }
bb-flasher-bcf = { path = "../bb-flasher-bcf", features = ["msp430", "cc1352p7"] }
zbus = { version = "5.5.0", default-features = false, features = ["tokio"], optional = true}
serde_with = { version = "3.12.0", optional = true }
udisks2 = { version = "0.3.1", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.60.0", features = ["Win32", "Win32_Storage", "Win32_Storage_FileSystem", "Win32_Security", "Win32_System", "Win32_System_IO", "Win32_System_Ioctl"] }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = { version = "3.2.0", optional = true }
nix = { version = "0.29.0", features = ["socket", "uio"], optional = true }

[features]
default = []
pb2_mspm0_raw = ["bb-flasher-pb2-mspm0"]
pb2_mspm0_dbus = ["dep:zbus", "dep:serde"]
serde = ["dep:serde"]
config = ["dep:serde_json", "serde", "dep:serde_with", "const-hex/serde", "semver/serde", "url/serde", "chrono/serde", "reqwest/json"]
macos_authopen = ["dep:security-framework", "dep:nix"]
