[package]
name = "bb-imager-cli"
description = "A streamlined tool for creating, flashing, and managing OS images for BeagleBoard devices."
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
bb-imager = { path = "../bb-imager" }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
indicatif = "0.17.8"
console = "0.15.10"
url = "2.5.4"
const-hex = "1.14.0"
clap_complete = "4.5.40"

[package.metadata.deb]
assets = [
	["target/release/bb-imager-cli", "/usr/bin/bb-imager-cli", "755"],
	["../target/man/*", "/usr/share/man/man1/", "644"],
	["../target/shell-completion/_bb-imager-cli", "/usr/share/zsh/site-functions/", "644"],
	["../target/shell-completion/bb-imager-cli.bash", "/usr/share/bash-completion/completions/bb-imager-cli", "644"]
]

[features]
default = []
pb2_mspm0 = [ "bb-imager/pb2_mspm0_raw" ]
