[package]
name = "bb-imager-gui"
description = "BeagleBoard Imaging Utility"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
iced = { version = "0.13.1", features = ["image", "svg", "tokio", "advanced", "lazy"] }
rfd = { version = "0.15.0", default-features = false, features = ["xdg-portal", "tokio"] }
bb-imager = { path = "../bb-imager", version = "0.0.3", features = ["config"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
iced_aw = { version = "0.11.0", default-features = false, features = ["badge"] }
image = "0.25.4"
tokio = { version = "1.41.0", default-features = false, features = ["macros"] }
webbrowser = "1.0.2"
notify-rust = "4.11.3"
url = { version = "2.5.2" }
chrono = { version = "0.4.38" }
futures-util = "0.3.31"
whoami = "1.5.2"
localzone = "0.3.1"
tokio-stream = "0.1.17"

[build-dependencies]
embed-resource = "2.5.0"

[package.metadata.deb]
assets = [
	["target/release/bb-imager-gui", "/usr/bin/bb-imager-gui", "755"],
	["assets/packages/linux/BeagleBoardImager.desktop", "/usr/share/applications/org.beagleboard.bb-imager.desktop", "644"],
	["assets/icons/icon.png", "/usr/share/icons/hicolor/128x128/apps/bb-imager.png", "644"]
]

[features]
pb2_mspm0 = ["bb-imager/pb2_mspm0_dbus"]

[target.'cfg(target_os = "linux")'.dependencies]
bb-imager = { path = "../bb-imager", version = "0.0.3", features = ["udisks2", "config"] }

[target.'cfg(target_os = "macos")'.dependencies]
bb-imager = { path = "../bb-imager", version = "0.0.3", features = ["macos_authopen", "config"] }
