[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image", "svg", "tokio"] }
rfd = { version = "0.14.1", default-features = false, features = ["xdg-portal", "tokio"] }
bb-imager = { path = "../bb-imager" }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
iced_aw = { version = "0.9.3", default-features = false, features = ["badge"] }
url = "2.5.2"
image = "0.25.2"
futures-util = "0.3.30"
tokio = { version = "1.39.2", default-features = false }

[package.metadata.appimage]
auto_link = true
auto_link_exclude_list = [
    "libc.so*",
		"libgcc_s.so",
		"ld-linux*",
		"libm.so*"
]
