[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image", "tokio"] }
rfd = "0.14.1"
bb-imager = { path = "../bb-imager" }
tokio = { version = "1.39.1", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.18"
