[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["image", "svg", "tokio", "advanced"] }
rfd = { version = "0.14.1", default-features = false, features = ["xdg-portal", "tokio"] }
bb-imager = { path = "../bb-imager" }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
iced_aw = { version = "0.10.0", default-features = false, features = ["badge"] }
image = "0.25.2"
tokio = { version = "1.39.2", default-features = false, features = ["macros"] }
webbrowser = "1.0.1"
notify-rust = "4.11.1"

[package.metadata.appimage]
auto_link = true
auto_link_exclude_list = [
    "libc.so*",
		"libgcc_s.so",
		"ld-linux*",
		"libm.so*"
]

[build-dependencies]
embed-resource = "2.4"
