[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["image", "lazy", "svg", "tokio"] }
rfd = "0.14.1"
bb-imager = { path = "../bb-imager" }
tokio = { version = "1.39.1" }
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
iced_aw = "0.9.3"
data_downloader = "0.2.0"
url = "2.5.2"
hex-literal = "0.4.1"
