name: Create Release artifacts

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x86_64:
    name: Build Artifacts - Linux x86_64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends libudev-dev
    - name: Install Cargo packager
      run: cargo install cargo-packager --locked
    - name: Build GUI Binar
      run: cargo build --locked --release -p bb-imager-gui -F bcf_cc1352p7 -F bcf_msp430
    - name: Create packages
      run: cargo packager -p bb-imager-gui -r -f appimage -f deb
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: bb-imager-gui/dist/*
