name: Create Release artifacts

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-native:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
    name: Build Artifacts - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends libudev-dev
    - name: Select rust toolchain
      run: rustup toolchain install stable --profile minimal
    - name: Use caching
      uses: Swatinem/rust-cache@v2
    - name: Install Cargo packager
      run: cargo install cargo-packager --locked
    - name: Build GUI Binary
      run: cargo build --locked --release -p bb-imager-gui -F bcf_cc1352p7 -F bcf_msp430
    - name: Create packages
      run: cargo packager -p bb-imager-gui -r -f appimage -f deb
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: bb-imager-gui/dist/*

  linux-cross:
    strategy:
      matrix:
        platform:
          - os-name: Linux arm
            runs-on: ubuntu-24.04
            target: armv7-unknown-linux-gnueabihf
            # cargo packager does not seem to work with appimage on arm32 right now
            formats: -f deb
            features: -F bcf_msp430 -F bcf_cc1352p7

    name: Release - ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Build binary
      uses: houseabsolute/actions-rust-cross@v1
      with:
        command: build
        target: ${{ matrix.platform.target }}
        args: "--locked --release ${{ matrix.platform.features }} -p bb-imager-gui"
        strip: true
    - name: Install Cargo packager
      run: cargo install cargo-packager --locked
    - name: Create packages
      run: cargo packager -p bb-imager-gui -r ${{ matrix.platform.formats }} --target ${{ matrix.platform.target }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: bb-imager-gui/dist/*
